version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/usr/local/apache2/htdocs/
        ports:
            - "8081:80"
